### ISSUE TITLE
setText not working lol

### ISSUE THREAD

**Issue by Soocyang** [Soocyang/Y2S2-GUI-Practical#2]
https://github.com/Soocyang/Y2S2-GUI-Practical/blob/786c75c7158179464285f4b3cfbd6142142b92a8/Practical4/src/P4Q4.java#L54

**Comment by rockneverendz** [comment]
https://github.com/Soocyang/Y2S2-GUI-Practical/blob/786c75c7158179464285f4b3cfbd6142142b92a8/Practical4/src/Password.java#L54

```
if (!errMessage.toString().isEmpty())
            throw new InvalidPasswordException(errorMessage.toString());
```
